# Generated by Django 3.1.7 on 2021-05-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210523_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
