# Generated by Django 3.1.7 on 2021-05-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_display_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='UserDP/'),
        ),
    ]
