# Generated by Django 3.1.7 on 2021-06-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210523_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_ID',
            field=models.CharField(default=1622969828.304763, max_length=256, null=True),
        ),
    ]
