# Generated by Django 3.1.7 on 2021-06-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210606_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_ID',
            field=models.CharField(default=1623065843.607389, max_length=256, null=True),
        ),
    ]
