# Generated by Django 3.1.7 on 2021-06-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210608_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_ID',
            field=models.CharField(default=1623125540.100273, max_length=256, null=True),
        ),
    ]
