# Generated by Django 3.1.7 on 2021-06-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_product',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
